config/routes.rb
SampleAppli::Application.routes.draw do
  resources :users

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',   :to => 'users#new'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :nom, :email, :password, :password_confirmation
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :nom, :presence => true,
					:length => { :maximum => 50 }
	validates :email, :presence => true,
					:format   => { :with => email_regex },
					:uniqueness => { :case_sensitive => false }
	# Crée automatique l'attribut virtuel 'password_confirmation'.
  	validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

    before_save :encrypt_password

    	# Retour true (vrai) si le mot de passe correspond.
		def has_password?(password_soumis)
		    # Compare encrypted_password avec la version cryptée de
		    # password_soumis.
		    
  			encrypted_password == encrypt(password_soumis)
		end

		def self.authenticate(email, submitted_password)
		   user = find_by_email(email)
		   return nil  if user.nil?
		   return user if user.has_password?(submitted_password)
		end

  	private

	    def encrypt_password
	      self.salt = make_salt if new_record?
	      self.encrypted_password = encrypt(password)
	    end

	    def encrypt(string)
	      secure_hash("#{salt}--#{string}")
	    end

	    def make_salt
	      secure_hash("#{Time.now.utc}--#{password}")
	    end

	    def secure_hash(string)
	      Digest::SHA2.hexdigest(string)
	    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
#encoding: utf-8
class PagesController < ApplicationController
  def home
  	@titre = "Accueil"
  end

  def contact
  	@titre = "Contact"
  end

  def about
  	@titre = "À Propos"
  end
  def help
  	@titre = "Aide"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@titre = "Inscription"
  end
  def show
  	@user = User.find(params[:id])
  	@titre = @user.nom
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# Retourner un titre basé sur la page.
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
        <% logo = image_tag("logo.png", :alt => "Application Exemple", :class => "round") %>
        <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Accueil", root_path %></li>
            <li><%= link_to "Aide", help_path %></li>
            <li><%= link_to "Inscription", signup_path %></li>
          </ul>
        </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= titre %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
    <h1>À Propos de nous</h1>
    <p>
      <a href="http://railstutorial.org/">Le Tutoriel Ruby on Rails</a>
      est un projet de livre et de screencasts pour apprendre le développement web
      avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. Ceci
      est l'Application Exemple du tutoriel.
    </p>
 

app/views/pages/contact.html.erb
    <h1>Contact</h1>
    <p>
      Contact Ruby on Rails Tutorial à propos de l'Application Exemple à
      <a href="http://railstutorial.org/feedback">feedback page</a>.
    </p>
 

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette Application Exemple, voyez le 
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<h1>Application Exemple</h1>

<p>
  C'est la page d'accuile pour l'application exemple du
  <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>.
</p>

<%= link_to "S'inscrire !", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>